VISION_USER=
VISION_PASSWORD=

AUTHORITY_URL=saxix.onmicrosoft.com
DATAMART_AZURE_CLIENT_ID=
DATAMART_AZURE_CLIENT_SECRET=
UNISET_AZURE_CLIENT_ID=
UNISET_AZURE_CLIENT_SECRET=

PGADMIN_DEFAULT_EMAIL=
PGADMIN_DEFAULT_PASSWORD=
POSTGRES_PASSWORD=

VERSION=latest

FLOWER_USER=
FLOWER_PWD=
